# This assumes binaries are present, see COPY directive.

FROM alpine AS chmodder
ARG TARGETARCH=amd64
COPY /artifacts/binaries-$TARGETARCH/templer /app/
RUN chmod +x /app/*

FROM gcr.io/distroless/cc
ARG TARGETARCH=amd64
COPY --from=chmodder /app/* /usr/local/bin/
ENTRYPOINT [ "/usr/local/bin/templer" ]
